### ISSUE TITLE
Installation update

### ISSUE THREAD

**Issue by kavikode** [Spartan-Velanjeri/UR-MiR-mobile-manipulator#1]
there seems to be at authentication failed message within the following
git clone https://git.rwth-aachen.de/rudresh.lonkar/mir_250_ros2/ src/mir_robot

Please update the readme file to ensure that installation will work on a local machine.
Thank you

**Comment by Spartan-Velanjeri** [comment]
Hi !
I've changed the clone link as it was put up by mistake. Now should be able to clone and continue the setup process. Let me know if you are still having issues.

**Comment by Spartan-Velanjeri** [comment]
Hi !
I've changed the clone link as it was put up by mistake. Now should be able to clone and continue the setup process. Feel free to reopen this issue if you are still having trouble.

**Comment by kavikode** [comment]
thank you so much! Some of the file locations were different, but I fixed it locally.
