### ISSUE TITLE
Converting xacro to urdf with base +arm+ gripper

### ISSUE THREAD

**Issue by kavikode** [Spartan-Velanjeri/UR-MiR-mobile-manipulator#2]
In src/mir_robot_ws/src/mir_robot/mir_robot/mir_description/urdf, I perform the following:

xacro mir.urdf.xacro > mir.urdf 

How can we convert xacro to urdf with the entire base +arm+ gripper as a single file?

thank you in advance!

**Comment by Spartan-Velanjeri** [comment]
ros2 run xacro xacro main.xacro -o main.urdf
You could try this. This should work

**Comment by Spartan-Velanjeri** [comment]
Closing issue for now. Reopen if issue persists
