### ISSUE TITLE
robotiq gripper control commands

### ISSUE THREAD

**Issue by kavikode** [Spartan-Velanjeri/UR-MiR-mobile-manipulator#3]
Will you please provide some code to open and close the gripper?

Also, can you please separate the commands for the different terminals for manipulation in different modes?

Thank you in advance!

**Comment by Spartan-Velanjeri** [comment]
The gripper code is something I haven't developed yet and I currently don't have the time for that unfortunately.

The manipulator codes are documented in a way you can run them individually in the different terminals
https://github.com/Spartan-Velanjeri/UR-MiR-mobile-manipulator?tab=readme-ov-file#manipulation-using-moveit2

Running the first two commands will allow you to access the manipulator. Every command beyond that is just with respect to particular applications.

**Comment by Gluca317** [comment]
Hello! I am a current student at Duke university. For our robotics project we are using your git repo for our project. We have been developing our own worlds and creating our own movement scripts that will use color to help it navigate for it on one computer. We have to run into an error with the Robot Model when using other computers where the robot arm is trapped inside and pointing under the robot. In addition to Gazebo, an RViz2 window pops up and I see that there is an error in the RobotModel drop-down under Displays. I see that all of the error messages start with "No transform from x to y".
We have followed all the steps and tried many times to make it work but to no avail. Any guidance would be very appreciated.

We have this issue when we run any command, such as the command:

ros2 launch mir_gazebo [mobile_manipulator.launch.py](http://mobile_manipulator.launch.py/) world:=maze

![image](https://github.com/user-attachments/assets/36437379-a52c-4fdc-9d27-5cb21f62f5c9)

![Screenshot from 2024-12-07 13-18-29](https://github.com/user-attachments/assets/8de3728e-b3b3-4978-9254-797d0d562c9f)

**Comment by Spartan-Velanjeri** [comment]
Hi @Gluca317 
Can you create a new issue for this problem you are facing?
