### ISSUE TITLE
Trouble with RobotModel

### ISSUE THREAD

**Issue by Gluca317** [Spartan-Velanjeri/UR-MiR-mobile-manipulator#4]
For our robotics project we are using your git repo for our project. We have been developing our own worlds and creating our own movement scripts that will use color to help it navigate for it on one computer. We have to run into an error with the Robot Model when using other computers where the robot arm is trapped inside and pointing under the robot. In addition to Gazebo, an RViz2 window pops up and I see that there is an error in the RobotModel drop-down under Displays. I see that all of the error messages start with "No transform from x to y".
We have followed all the steps and tried many times to make it work but to no avail. Any guidance would be very appreciated.

We have this issue when we run any command, such as the command:

ros2 launch mir_gazebo [mobile_manipulator.launch.py](http://mobile_manipulator.launch.py/) world:=maze

![image](https://github.com/user-attachments/assets/a518e83f-da79-4c21-a177-7963a87a5e48)
![image](https://github.com/user-attachments/assets/f5fa15c9-ccaf-4a0b-8e03-7ab6e80c4d83)

**Comment by Spartan-Velanjeri** [comment]
Could you also attach the terminal log when you run the above launch file?

**Comment by Gluca317** [comment]
labuser@gl3linux:~/ros2_ws$ ros2 launch mir_gazebo mobile_manipulator.launch.py world:=maze
[INFO] [launch]: All log files can be found below /home/labuser/.ros/log/2024-12-07-16-55-24-331838-gl3linux-98166
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ros2-1]: process started with pid [98176]
[INFO] [ros2-2]: process started with pid [98178]
[INFO] [gzserver-3]: process started with pid [98180]
[INFO] [gzclient-4]: process started with pid [98182]
[INFO] [robot_state_publisher-5]: process started with pid [98184]
[INFO] [spawn_entity.py-6]: process started with pid [98186]
[INFO] [laserscan_multi_merger-7]: process started with pid [98188]
[INFO] [spawner-8]: process started with pid [98190]
[INFO] [rviz2-9]: process started with pid [98192]
[INFO] [xterm-10]: process started with pid [98194]
[robot_state_publisher-5] [INFO] [1733608525.538799815] [robot_state_publisher]: got segment back_laser_link
[robot_state_publisher-5] [INFO] [1733608525.538910206] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-5] [INFO] [1733608525.538920826] [robot_state_publisher]: got segment base_link
[robot_state_publisher-5] [INFO] [1733608525.538927206] [robot_state_publisher]: got segment bl_caster_rotation_link
[robot_state_publisher-5] [INFO] [1733608525.538934020] [robot_state_publisher]: got segment bl_caster_wheel_link
[robot_state_publisher-5] [INFO] [1733608525.538940534] [robot_state_publisher]: got segment br_caster_rotation_link
[robot_state_publisher-5] [INFO] [1733608525.538946543] [robot_state_publisher]: got segment br_caster_wheel_link
[robot_state_publisher-5] [INFO] [1733608525.538953066] [robot_state_publisher]: got segment camera_mount
[robot_state_publisher-5] [INFO] [1733608525.538959442] [robot_state_publisher]: got segment fl_caster_rotation_link
[robot_state_publisher-5] [INFO] [1733608525.538965284] [robot_state_publisher]: got segment fl_caster_wheel_link
[robot_state_publisher-5] [INFO] [1733608525.538970920] [robot_state_publisher]: got segment fr_caster_rotation_link
[robot_state_publisher-5] [INFO] [1733608525.538976482] [robot_state_publisher]: got segment fr_caster_wheel_link
[robot_state_publisher-5] [INFO] [1733608525.538982534] [robot_state_publisher]: got segment front_laser_link
[robot_state_publisher-5] [INFO] [1733608525.538988970] [robot_state_publisher]: got segment imu_frame
[robot_state_publisher-5] [INFO] [1733608525.538994864] [robot_state_publisher]: got segment imu_link
[robot_state_publisher-5] [INFO] [1733608525.539000822] [robot_state_publisher]: got segment left_wheel_link
[robot_state_publisher-5] [INFO] [1733608525.539007310] [robot_state_publisher]: got segment power_unit
[robot_state_publisher-5] [INFO] [1733608525.539012887] [robot_state_publisher]: got segment realsense_accel_frame
[robot_state_publisher-5] [INFO] [1733608525.539018935] [robot_state_publisher]: got segment realsense_accel_optical_frame
[robot_state_publisher-5] [INFO] [1733608525.539024918] [robot_state_publisher]: got segment realsense_bottom_screw_frame
[robot_state_publisher-5] [INFO] [1733608525.539030920] [robot_state_publisher]: got segment realsense_color_frame
[robot_state_publisher-5] [INFO] [1733608525.539037083] [robot_state_publisher]: got segment realsense_color_optical_frame
[robot_state_publisher-5] [INFO] [1733608525.539043198] [robot_state_publisher]: got segment realsense_depth_frame
[robot_state_publisher-5] [INFO] [1733608525.539049493] [robot_state_publisher]: got segment realsense_depth_optical_frame
[robot_state_publisher-5] [INFO] [1733608525.539055320] [robot_state_publisher]: got segment realsense_gyro_frame
[robot_state_publisher-5] [INFO] [1733608525.539061560] [robot_state_publisher]: got segment realsense_gyro_optical_frame
[robot_state_publisher-5] [INFO] [1733608525.539067775] [robot_state_publisher]: got segment realsense_infra1_frame
[robot_state_publisher-5] [INFO] [1733608525.539074465] [robot_state_publisher]: got segment realsense_infra1_optical_frame
[robot_state_publisher-5] [INFO] [1733608525.539080533] [robot_state_publisher]: got segment realsense_infra2_frame
[robot_state_publisher-5] [INFO] [1733608525.539086560] [robot_state_publisher]: got segment realsense_infra2_optical_frame
[robot_state_publisher-5] [INFO] [1733608525.539093120] [robot_state_publisher]: got segment realsense_link
[robot_state_publisher-5] [INFO] [1733608525.539106556] [robot_state_publisher]: got segment right_wheel_link
[robot_state_publisher-5] [INFO] [1733608525.539113211] [robot_state_publisher]: got segment surface
[robot_state_publisher-5] [INFO] [1733608525.539119609] [robot_state_publisher]: got segment ur_base
[robot_state_publisher-5] [INFO] [1733608525.539126348] [robot_state_publisher]: got segment ur_base_link
[robot_state_publisher-5] [INFO] [1733608525.539133116] [robot_state_publisher]: got segment ur_base_link_inertia
[robot_state_publisher-5] [INFO] [1733608525.539139550] [robot_state_publisher]: got segment ur_flange
[robot_state_publisher-5] [INFO] [1733608525.539146545] [robot_state_publisher]: got segment ur_forearm_link
[robot_state_publisher-5] [INFO] [1733608525.539153092] [robot_state_publisher]: got segment ur_ft_frame
[robot_state_publisher-5] [INFO] [1733608525.539160037] [robot_state_publisher]: got segment ur_shoulder_link
[robot_state_publisher-5] [INFO] [1733608525.539166956] [robot_state_publisher]: got segment ur_tool0
[robot_state_publisher-5] [INFO] [1733608525.539173465] [robot_state_publisher]: got segment ur_upper_arm_link
[robot_state_publisher-5] [INFO] [1733608525.539179850] [robot_state_publisher]: got segment ur_wrist_1_link
[robot_state_publisher-5] [INFO] [1733608525.539186780] [robot_state_publisher]: got segment ur_wrist_2_link
[robot_state_publisher-5] [INFO] [1733608525.539192108] [robot_state_publisher]: got segment ur_wrist_3_link
[robot_state_publisher-5] [INFO] [1733608525.539197295] [robot_state_publisher]: got segment us_1_frame
[robot_state_publisher-5] [INFO] [1733608525.539202314] [robot_state_publisher]: got segment us_2_frame
[robot_state_publisher-5] [INFO] [1733608525.539207514] [robot_state_publisher]: got segment virtual_laser_link
[robot_state_publisher-5] [INFO] [1733608525.539248308] [robot_state_publisher]: got segment world
[spawner-8] [INFO] [1733608526.318666061] [spawner_joint_trajectory_controller]: waiting for service /controller_manager/list_controllers to become available...
[spawn_entity.py-6] [INFO] [1733608526.324768232] [spawn_entity]: Spawn Entity started
[spawn_entity.py-6] [INFO] [1733608526.325078293] [spawn_entity]: Loading entity published on topic robot_description
[spawn_entity.py-6] /opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/qos.py:307: UserWarning: DurabilityPolicy.RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL is deprecated. Use DurabilityPolicy.TRANSIENT_LOCAL instead.
[spawn_entity.py-6]   warnings.warn(
[spawn_entity.py-6] [INFO] [1733608526.327561735] [spawn_entity]: Waiting for entity xml on robot_description
[spawn_entity.py-6] [INFO] [1733608526.518856661] [spawn_entity]: Waiting for service /spawn_entity, timeout = 30
[spawn_entity.py-6] [INFO] [1733608526.519192257] [spawn_entity]: Waiting for service /spawn_entity
[ros2-1] [INFO] [1733608526.819298694] [_ros2cli_98176]: waiting for service /controller_manager/load_controller to become available...
[laserscan_multi_merger-7] [WARN] [1733608527.665795274] [mir_laser_scan_merger]: New subscription discovered on topic '/scan', requesting incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY
[ros2-2] [INFO] [1733608527.862661525] [_ros2cli_98178]: waiting for service /controller_manager/load_controller to become available...
[spawn_entity.py-6] [INFO] [1733608528.025034480] [spawn_entity]: Calling service /spawn_entity
[spawn_entity.py-6] [INFO] [1733608529.020072781] [spawn_entity]: Spawn status: SpawnEntity: Successfully spawned entity [mir_robot]
[spawn_entity.py-6] [INFO] [1733608529.020497749] [spawn_entity]: Waiting for shutdown to delete entity [mir_robot]
[gzserver-3] [INFO] [1733608529.649221591] [camera.realsenseimu]: <initial_orientation_as_reference> is unset, using default value of false to comply with REP 145 (world as orientation reference)
[gzserver-3] [INFO] [1733608529.729970473] [GazeboRealsenseNode]: Realsense Gazebo ROS plugin loading.
[gzserver-3] 
[gzserver-3] RealSensePlugin: The realsense_camera plugin is attach to model mir_robot
[gzserver-3] [INFO] [1733608529.756910352] [GazeboRealsenseNode]: Loaded Realsense Gazebo ROS plugin.
[laserscan_multi_merger-7] [INFO] [1733608530.552233502] [mir_laser_scan_merger]: Subscribing to 2 topics.
[laserscan_multi_merger-7] [INFO] [1733608530.554142571] [mir_laser_scan_merger]: Subscribed to /b_scan.
[laserscan_multi_merger-7] [INFO] [1733608530.555561442] [mir_laser_scan_merger]: Subscribed to /f_scan.
[spawner-8] [WARN] [1733608536.332759766] [spawner_joint_trajectory_controller]: Could not contact service /controller_manager/list_controllers
[spawner-8] [INFO] [1733608536.334294504] [spawner_joint_trajectory_controller]: waiting for service /controller_manager/list_controllers to become available...
[ros2-1] [WARN] [1733608536.833798940] [_ros2cli_98176]: Could not contact service /controller_manager/load_controller
[ros2-1] [INFO] [1733608536.834843966] [_ros2cli_98176]: waiting for service /controller_manager/load_controller to become available...
[ros2-2] [WARN] [1733608537.877082428] [_ros2cli_98178]: Could not contact service /controller_manager/load_controller
[ros2-2] [INFO] [1733608537.878304201] [_ros2cli_98178]: waiting for service /controller_manager/load_controller to become available...
[spawner-8] [WARN] [1733608546.348764785] [spawner_joint_trajectory_controller]: Could not contact service /controller_manager/list_controllers
[spawner-8] [INFO] [1733608546.349994833] [spawner_joint_trajectory_controller]: waiting for service /controller_manager/list_controllers to become available...
[ros2-1] [WARN] [1733608546.849170151] [_ros2cli_98176]: Could not contact service /controller_manager/load_controller
[ros2-1] [INFO] [1733608546.850287574] [_ros2cli_98176]: waiting for service /controller_manager/load_controller to become available...
[ros2-2] [WARN] [1733608547.893157344] [_ros2cli_98178]: Could not contact service /controller_manager/load_controller
[ros2-2] [INFO] [1733608547.894571784] [_ros2cli_98178]: waiting for service /controller_manager/load_controller to become available...

**Comment by Spartan-Velanjeri** [comment]
Have you installed these packages already?
```
sudo apt-get install ros-humble-ros2-control
sudo apt-get install ros-humble-ros2-controllers
sudo apt-get install ros-humble-gazebo-ros-pkgs
sudo apt-get install ros-humble-gazebo-ros2-control
```

**Comment by Gluca317** [comment]
That worked thank you very much that last line was somehow what we forgot
